# Generated by Django 3.0.6 on 2020-12-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep', models.CharField(max_length=20)),
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('image', models.ImageField(upload_to='static/photo/')),
                ('pic_id', models.AutoField(primary_key=True, serialize=False, verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('stafftype', models.CharField(max_length=15)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False, verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usersreal',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(verbose_name=15)),
                ('landnumber', models.IntegerField(verbose_name=15)),
                ('password', models.CharField(max_length=50)),
                ('is_activate', models.IntegerField()),
                ('is_valid', models.IntegerField()),
                ('is_admin', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Picture')),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Department')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Staff')),
            ],
        ),
    ]
