# Generated by Django 3.0.6 on 2020-12-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201208_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=6),
        ),
    ]
