# Generated by Django 3.0.6 on 2020-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201208_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.CharField(max_length=15),
        ),
    ]
