# Generated by Django 3.0.6 on 2020-12-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201208_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='stafftype',
            field=models.CharField(max_length=40),
        ),
    ]
