# Generated by Django 3.0.6 on 2020-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201208_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreal',
            name='is_activate',
            field=models.IntegerField(verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='is_admin',
            field=models.IntegerField(verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='is_valid',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
