# Generated by Django 3.0.6 on 2020-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201208_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreal',
            name='landnumber',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='phonenumber',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
