# Generated by Django 3.0.6 on 2020-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201208_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersreal',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='landnumber',
            field=models.CharField(max_length=20),
        ),
    ]
