# Generated by Django 3.0.6 on 2020-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20201208_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersreal',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='usersreal',
            name='phonenumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
