# Generated by Django 3.0.6 on 2020-12-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20201208_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersreal',
            name='is_admin',
            field=models.IntegerField(default=1, verbose_name=6),
            preserve_default=False,
        ),
    ]
