# Generated by Django 3.0.6 on 2020-12-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_usersreal_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreal',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Department'),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Picture'),
        ),
    ]
