# Generated by Django 3.0.6 on 2020-12-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20201208_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_id',
            new_name='deptid',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='pic_id',
            new_name='picid',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='staffid',
        ),
        migrations.RenameField(
            model_name='usersreal',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='usersreal',
            old_name='pic_id',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='usersreal',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
