# Generated by Django 3.0.6 on 2020-12-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20201209_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='profilefield',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='is_activate',
            field=models.IntegerField(default=0, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='is_admin',
            field=models.IntegerField(default=0, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='is_valid',
            field=models.IntegerField(default=0, verbose_name=6),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='webapp.Picture'),
        ),
    ]
