# Generated by Django 3.0.6 on 2020-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20201221_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='profilefield',
            field=models.ImageField(blank=True, null=True, upload_to='static/phot0/'),
        ),
    ]
