# Generated by Django 3.0.6 on 2020-12-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201221_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='profilefield',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo/'),
        ),
        migrations.AlterField(
            model_name='usersreal',
            name='pic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='webapp.Picture'),
        ),
    ]
