# Generated by Django 3.0.6 on 2020-12-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20201221_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreal',
            name='pic',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='webapp.Picture'),
        ),
    ]
