# Generated by Django 3.0.6 on 2020-12-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20201221_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
    ]
