# Generated by Django 3.0.6 on 2021-01-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersreal',
            name='pic',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='webapp.Picture'),
        ),
    ]
